# Generated by Django 6.1 on 2026-08-13 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_company_options'),
        ('trips', '0002_alter_trip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('issue_type', models.CharField(choices=[('pickup', 'Pickup'), ('transit', 'Transit'), ('unloading', 'Unloading'), ('traffic_penalty', 'Traffic Penalty')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('note', models.TextField()),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='trips.trip')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='trips.tripstop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
