# Generated by Django 6.1 on 2026-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripissue',
            name='penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tripissue',
            name='penalty_challan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tripissue',
            name='penalty_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripissue',
            name='penalty_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
