# Generated by Django 6.1 on 2026-08-12 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('aadhar_doc_url', models.URLField(blank=True, null=True)),
                ('aadhar_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('aadhar_verified_by', models.UUIDField(blank=True, null=True)),
                ('aadhar_verified_at', models.DateTimeField(blank=True, null=True)),
                ('aadhar_rejection_note', models.TextField(blank=True, null=True)),
                ('dl_doc_url', models.URLField(blank=True, null=True)),
                ('dl_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('dl_expiry_date', models.DateField(blank=True, null=True)),
                ('dl_allowed_categories', models.JSONField(default=list)),
                ('dl_verified_by', models.UUIDField(blank=True, null=True)),
                ('dl_verified_at', models.DateTimeField(blank=True, null=True)),
                ('dl_rejection_note', models.TextField(blank=True, null=True)),
                ('police_doc_url', models.URLField(blank=True, null=True)),
                ('police_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('police_verified_by', models.UUIDField(blank=True, null=True)),
                ('police_verified_at', models.DateTimeField(blank=True, null=True)),
                ('police_rejection_note', models.TextField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('locked_dl_expired', 'Locked — DL Expired'), ('disabled', 'Disabled')], default='active', max_length=30)),
                ('current_vehicle_id', models.UUIDField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company_id', 'phone_number'), name='unique_driver_phone_per_company')],
            },
        ),
    ]
