# Generated by Django 6.1 on 2026-08-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('locked_dl_expired', 'Locked — DL Expired'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=30),
        ),
    ]
