# Generated by Django 6.1 on 2026-09-16 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_duty_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverKyc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aadhar_doc_url', models.URLField(blank=True, null=True)),
                ('aadhar_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('aadhar_verified_by', models.UUIDField(blank=True, null=True)),
                ('aadhar_verified_at', models.DateTimeField(blank=True, null=True)),
                ('aadhar_rejection_note', models.TextField(blank=True, null=True)),
                ('dl_doc_url', models.URLField(blank=True, null=True)),
                ('dl_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('dl_expiry_date', models.DateField(blank=True, null=True)),
                ('dl_allowed_categories', models.JSONField(default=list)),
                ('dl_verified_by', models.UUIDField(blank=True, null=True)),
                ('dl_verified_at', models.DateTimeField(blank=True, null=True)),
                ('dl_rejection_note', models.TextField(blank=True, null=True)),
                ('police_doc_url', models.URLField(blank=True, null=True)),
                ('police_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('police_verified_by', models.UUIDField(blank=True, null=True)),
                ('police_verified_at', models.DateTimeField(blank=True, null=True)),
                ('police_rejection_note', models.TextField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='drivers.driver')),
            ],
        ),
    ]
