# Generated by Django 6.1 on 2026-09-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_copy_kyc_data'),
    ]

    operations = [
        migrations.RemoveField(model_name='driver', name='aadhar_doc_url'),
        migrations.RemoveField(model_name='driver', name='aadhar_status'),
        migrations.RemoveField(model_name='driver', name='aadhar_verified_by'),
        migrations.RemoveField(model_name='driver', name='aadhar_verified_at'),
        migrations.RemoveField(model_name='driver', name='aadhar_rejection_note'),
        migrations.RemoveField(model_name='driver', name='dl_doc_url'),
        migrations.RemoveField(model_name='driver', name='dl_status'),
        migrations.RemoveField(model_name='driver', name='dl_expiry_date'),
        migrations.RemoveField(model_name='driver', name='dl_allowed_categories'),
        migrations.RemoveField(model_name='driver', name='dl_verified_by'),
        migrations.RemoveField(model_name='driver', name='dl_verified_at'),
        migrations.RemoveField(model_name='driver', name='dl_rejection_note'),
        migrations.RemoveField(model_name='driver', name='police_doc_url'),
        migrations.RemoveField(model_name='driver', name='police_status'),
        migrations.RemoveField(model_name='driver', name='police_verified_by'),
        migrations.RemoveField(model_name='driver', name='police_verified_at'),
        migrations.RemoveField(model_name='driver', name='police_rejection_note'),
    ]
