# Generated by Django 6.1 on 2026-09-17 00:00
#
# VehicleType/Vehicle/VehicleDocument moved here from the now-removed
# `vehicles` app — Vehicle is driver-operated, and Driver/Vehicle were
# always going to be queried together (see MatchingService), so keeping
# them as separate top-level apps bought nothing. This project has no
# deployed database, so this is a fresh CreateModel rather than a
# state-only app move: an existing local dev DB from before this change
# should be recreated (`docker compose down -v && up`, then migrate) —
# don't try to fast-forward it.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_remove_driver_kyc_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('two_wheeler', '2 Wheeler'), ('three_wheeler', '3 Wheeler'), ('four_wheeler', '4 Wheeler')], max_length=20)),
                ('default_capacity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('icon_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_min_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=20)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('current_driver_id', models.UUIDField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='drivers.vehicletype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance'), ('fitness', 'Fitness'), ('rc', 'RC'), ('purchase', 'Purchase'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicletype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company_id', 'name'), name='unique_vehicle_type_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company_id', 'registration_number'), name='unique_registration_per_company'),
        ),
    ]
