# Generated by Django 6.1 on 2026-09-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_vehicle_owner_and_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'wallet entry', 'verbose_name_plural': 'wallet ledger'},
        ),
    ]
