# Generated by Django 6.1 on 2026-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_alter_wallettransaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='kind',
            field=models.CharField(choices=[('trip_earning', 'Trip earning'), ('bonus', 'Bonus'), ('penalty', 'Penalty'), ('payout', 'Payout'), ('adjustment', 'Adjustment'), ('cod_cash', 'Cash collected')], max_length=20),
        ),
    ]
