# Generated by Django 6.1 on 2026-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='webhook_signing_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
