# Generated by Django 6.1 on 2026-09-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'admin login'},
        ),
        migrations.AlterModelOptions(
            name='apiclient',
            options={'verbose_name': 'API client'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'companies'},
        ),
    ]
