# Generated by Django 6.1 on 2026-09-27 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adminuser_options_alter_apiclient_options_and_more'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='other', max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=40)),
                ('address', models.CharField(max_length=255)),
                ('details', models.CharField(blank=True, default='', max_length=120)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to='booking.customer')),
            ],
            options={
                'ordering': ['kind', '-updated_at'],
            },
        ),
    ]
