# Generated by Django 6.1 on 2026-08-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicledocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['-created_at']},
        ),
    ]
