# Generated by Django 6.1 on 2026-08-14 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apiclient_webhook_signing_secret_and_more'),
        ('vehicles', '0002_alter_vehicle_options_alter_vehicledocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocumentExpiryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('detected_at', models.DateTimeField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='vehicles.vehicledocument')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_expiry_alerts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-detected_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('acknowledged', False)), fields=('document',), name='unique_open_expiry_alert_per_document')],
            },
        ),
    ]
