# Generated by Django 6.1 on 2026-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicledocumentexpiryalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='storage_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='storage_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='storage_unit',
            field=models.CharField(blank=True, choices=[('feet', 'Feet'), ('cm', 'cm'), ('inches', 'Inches')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='storage_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
