# Generated by Django 6.1 on 2026-08-14 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('driver_id', models.UUIDField()),
                ('response_body', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='idempotency_created_6e6049_idx')],
                'constraints': [models.UniqueConstraint(fields=('driver_id', 'key'), name='unique_idempotency_key_per_driver')],
            },
        ),
    ]
