# Generated by Django 6.1 on 2026-08-14 04:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idempotency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='response_body',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
