# Generated by Django 6.1 on 2026-08-13 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_company_options'),
        ('drivers', '0001_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0002_alter_vehicle_options_alter_vehicledocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shift_date', models.DateField()),
                ('start_odometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=20)),
                ('total_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_working_minutes', models.IntegerField(blank=True, null=True)),
                ('cleanliness_photo_url', models.URLField(blank=True, null=True)),
                ('charging_plugged_photo_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('driver',), name='unique_active_shift_per_driver')],
            },
        ),
        migrations.CreateModel(
            name='TripAnomalyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_id', models.UUIDField()),
                ('alert_type', models.CharField(choices=[('stationary_too_long', 'Stationary Too Long'), ('wrong_direction', 'Wrong Direction')], max_length=30)),
                ('details', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='trips.trip')),
            ],
            options={
                'ordering': ['-detected_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('acknowledged', False)), fields=('trip', 'alert_type'), name='unique_open_alert_per_trip_and_type')],
            },
        ),
        migrations.CreateModel(
            name='TripLocationPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('vehicle_id', models.UUIDField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(choices=[('driver_phone', 'Driver Phone'), ('hardware_gps', 'Hardware GPS')], default='driver_phone', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='trips.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle_id', '-recorded_at'], name='tracking_tr_vehicle_3ab09f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripPause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('lunch', 'Lunch'), ('recharge', 'Recharge'), ('driver_break', 'Driver Break')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='trips.trip')),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('trip',), name='unique_open_pause_per_trip')],
            },
        ),
    ]
