# Generated by Django 6.1 on 2026-08-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_drivershift_fixed_start_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplocationping',
            name='distance_from_previous_km',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
