# Generated by Django 6.1 on 2026-08-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_tripplocationping_distance_from_previous_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivershift',
            name='fixed_start_label',
        ),
        migrations.RemoveField(
            model_name='drivershift',
            name='fixed_start_latitude',
        ),
        migrations.RemoveField(
            model_name='drivershift',
            name='fixed_start_longitude',
        ),
        migrations.DeleteModel(
            name='VehicleStartPoint',
        ),
    ]
