# Generated by Django 6.1 on 2026-08-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apiclient_webhook_signing_secret_and_more'),
        ('tracking', '0004_remove_vehicle_start_point'),
        ('trips', '0004_trip_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='gps_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='needs_variance_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='variance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tripanomalyalert',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='tracking.drivershift'),
        ),
        migrations.AlterField(
            model_name='tripanomalyalert',
            name='alert_type',
            field=models.CharField(choices=[('stationary_too_long', 'Stationary Too Long'), ('wrong_direction', 'Wrong Direction'), ('gps_offline', 'GPS Offline')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tripanomalyalert',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='trips.trip'),
        ),
        migrations.AddConstraint(
            model_name='tripanomalyalert',
            constraint=models.UniqueConstraint(condition=models.Q(('acknowledged', False)), fields=('shift', 'alert_type'), name='unique_open_alert_per_shift_and_type'),
        ),
    ]
