# Generated by Django 6.1 on 2026-09-16 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_company_options'),
        ('drivers', '0006_vehicle_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('no_driver_available', 'No Driver Available'), ('assigned', 'Assigned'), ('arrived_at_pickup', 'Arrived At Pickup'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=30)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_contact_name', models.CharField(blank=True, max_length=150)),
                ('pickup_contact_phone', models.CharField(blank=True, max_length=20)),
                ('drop_address', models.CharField(max_length=255)),
                ('drop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_contact_name', models.CharField(blank=True, max_length=150)),
                ('drop_contact_phone', models.CharField(blank=True, max_length=20)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('route_polyline', models.TextField(blank=True)),
                ('polyline_precision', models.PositiveSmallIntegerField(default=6)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('total_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.CharField(blank=True, choices=[('company', 'Company'), ('driver', 'Driver'), ('system', 'System')], max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.vehicletype')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['company', 'status'], name='trips_trip_company_8dc10a_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'status'], name='trips_trip_driver__692693_idx'),
        ),
    ]
