# Generated by Django 6.1 on 2026-08-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('collecting_pickups', 'Collecting Pickups'), ('pickups_locked', 'Pickups Locked'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='collecting_pickups', max_length=30),
        ),
    ]
