# Generated by Django 6.1 on 2026-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cod_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_mode',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('cod', 'Cash on Delivery')], default='prepaid', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
