# Generated by Django 6.1 on 2026-09-20 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options'),
        ('drivers', '0007_driver_onboarding_and_wallet'),
        ('trips', '0002_add_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_earning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='invoice_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='trip',
            name='verify_items',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TripItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('not_delivered', 'Not delivered')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('proof_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('driver_note', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.trip')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drivers.driver')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
