# Generated by Django 6.1 on 2026-08-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='location_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='location_mismatch_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
