# Generated by Django 6.1 on 2026-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_items_and_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_qr_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_qr_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
