# Generated by Django 6.1 on 2026-08-17 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apiclient_webhook_signing_secret_and_more'),
        ('trips', '0003_tripstop_location_mismatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('photo_type', models.CharField(choices=[('pickup', 'Pickup'), ('before_loading', 'Before Loading'), ('loaded_vehicle', 'Loaded Vehicle'), ('delivery', 'Delivered Goods'), ('goods_after_delivery', 'Goods After Delivery'), ('signed_challan', 'Signed Delivery Challan'), ('dc', 'Delivery Challan'), ('other', 'Other')], max_length=25)),
                ('photo_url', models.URLField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('trip_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.tripstop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
