# Generated by Django 6.1 on 2026-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_payment_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bonus_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
