# Generated by Django 6.1 on 2026-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_pickup_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='delivery_photo',
            field=models.CharField(choices=[('none', 'None'), ('order', 'One photo of the whole order'), ('per_item', 'One photo of every item')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='delivery_photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
