# Generated by Django 6.1 on 2026-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_delivery_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
