# Generated by Django 6.1 on 2026-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='delivery_otp',
            field=models.BooleanField(default=False),
        ),
    ]
