# Generated by Django 6.1 on 2026-09-25 13:19

from django.db import migrations, models


def number_existing_trips(apps, schema_editor):
    """Gives trips booked before order numbers existed one, oldest first."""
    from django.utils import timezone

    Trip = apps.get_model("trips", "Trip")
    TripNumber = apps.get_model("trips", "TripNumber")
    for trip in Trip.objects.filter(order_number__isnull=True).order_by("created_at"):
        n = TripNumber.objects.create().pk
        trip.order_number = f"OD{timezone.localdate(trip.created_at):%Y%m%d}000{n}"
        trip.save(update_fields=["order_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_delivery_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(number_existing_trips, migrations.RunPython.noop),
    ]
