# Generated by Django 6.1 on 2026-09-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'verbose_name': 'order'},
        ),
        migrations.AlterModelOptions(
            name='tripitem',
            options={'ordering': ['position', 'created_at'], 'verbose_name': 'order item'},
        ),
    ]
