# Generated by Django 6.1 on 2026-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_trip_options_alter_tripitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='voice_note_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='voice_note_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trip',
            name='delivery_photo',
            field=models.CharField(choices=[('none', 'None'), ('order', 'One photo of the whole order'), ('per_item', 'One photo of every item'), ('both', 'The whole order and every item')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_photo',
            field=models.CharField(choices=[('none', 'None'), ('order', 'One photo of the whole order'), ('per_item', 'One photo of every item'), ('both', 'The whole order and every item')], default='none', max_length=20),
        ),
    ]
