# Generated by Django 6.1 on 2026-09-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('trips', '0012_both_photos_voice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='booking.customer'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('driver', 'Driver'), ('system', 'System'), ('customer', 'Customer')], max_length=20),
        ),
    ]
