# Generated by Django 6.1 on 2026-09-25 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


def stops_for_existing_trips(apps, schema_editor):
    """Every trip before multi-stop gets its two stops: pickup, then drop."""
    Trip = apps.get_model("trips", "Trip")
    TripStop = apps.get_model("trips", "TripStop")
    rows = []
    for t in Trip.objects.all().iterator():
        done = t.status == "completed"
        started = t.started_at is not None
        rows.append(TripStop(company_id=t.company_id, trip_id=t.pk, position=0, kind="pickup", address=t.pickup_address,
                             lat=t.pickup_lat, lng=t.pickup_lng, contact_name=t.pickup_contact_name,
                             contact_phone=t.pickup_contact_phone, status="done" if started else "pending",
                             arrived_at=t.arrived_at_pickup_at, done_at=t.started_at))
        rows.append(TripStop(company_id=t.company_id, trip_id=t.pk, position=1, kind="drop", address=t.drop_address,
                             lat=t.drop_lat, lng=t.drop_lng, contact_name=t.drop_contact_name,
                             contact_phone=t.drop_contact_phone, reference=t.order_number or "",
                             status="done" if done else "pending", done_at=t.completed_at))
    TripStop.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adminuser_options_alter_apiclient_options_and_more'),
        ('trips', '0013_trip_customer_alter_trip_cancelled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('arrived', 'Driver arrived'), ('done', 'Done')], default='pending', max_length=10)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'position'), name='unique_stop_position_per_trip')],
            },
        ),
        migrations.RunPython(stops_for_existing_trips, migrations.RunPython.noop),
    ]
