# Generated by Django 6.1 on 2026-08-14 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_apiclient_webhook_signing_secret_and_more'),
        ('drivers', '0002_alter_driver_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='drivers.driver')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('driver', 'fcm_token'), name='unique_driver_device_token')],
            },
        ),
    ]
